In [1]:
import pandas as pd

In [2]:
import pandas as pd
import glob

data_nueva = pd.read_csv('data/GoodReads_100k_books.csv')
data_nueva

,author,bookformat,desc,genre,img,isbn,isbn13,link,pages,rating,reviews,title,totalratings
0,Laurence M. Hauptman,Hardcover,Reveals that several hundred thousand Indians ...,"History,Military History,Civil War,American Hi...",https://i.gr-assets.com/images/S/compressed.ph...,002914180X,9.78E+12,https://goodreads.com/book/show/1001053.Betwee...,0,3.52,5,Between Two Fires: American Indians in the Civ...,33
1,"Charlotte Fiell,Emmanuelle Dirix",Paperback,Fashion Sourcebook - 1920s is the first book i...,"Couture,Fashion,Historical,Art,Nonfiction",https://i.gr-assets.com/images/S/compressed.ph...,1906863482,9.78E+12,https://goodreads.com/book/show/10010552-fashi...,576,4.51,6,Fashion Sourcebook 1920s,41
2,Andy Anderson,Paperback,The seminal history and analysis of the Hungar...,"Politics,History",https://i.gr-assets.com/images/S/compressed.ph...,948984147,9.78E+12,https://goodreads.com/book/show/1001077.Hungar...,124,4.15,2,Hungary 56,26
3,Carlotta R. Anderson,Hardcover,"""All-American Anarchist"" chronicles the life a...","Labor,History",https://i.gr-assets.com/images/S/compressed.ph...,814327079,9.78E+12,https://goodreads.com/book/show/1001079.All_Am...,324,3.83,1,All-American Anarchist: Joseph A. Labadie and ...,6
4,Jean Leveille,NaN,"Aujourdâ€™hui, lâ€™oiseau nous invite Ã sa ta...",NaN,https://i.gr-assets.com/images/S/compressed.ph...,2761920813,NaN,https://goodreads.com/book/show/10010880-les-o...,177,4.00,1,Les oiseaux gourmands,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Simon Monk,ebook,Design custom printed circuit boards with EAGL...,NaN,https://i.gr-assets.com/images/S/compressed.ph...,71819266,9.78007E+12,https://goodreads.com/book/show/17320181-make-...,304,4.07,7,Make Your Own PCBs with Eagle: From Schematic ...,56
99996,"Tracie L. Miller-Nobles,Brenda L. Mattison,Ell...",Hardcover,"Redefining tradition in learning accounting. ,...",NaN,https://i.gr-assets.com/images/S/compressed.ph...,133251241,9.78013E+12,https://goodreads.com/book/show/17320260-horng...,1645,4.05,1,Horngren's Financial & Managerial Accounting,38
99997,C. John Miller,Paperback,In these warm reflections on his own growth as...,"Christianity,Evangelism,Christian,Religion,The...",https://i.gr-assets.com/images/S/compressed.ph...,875523919,9.78088E+12,https://goodreads.com/book/show/173203.A_Faith...,160,4.27,20,A Faith Worth Sharing: A Lifetime of Conversat...,122
99998,Albert Marrin,Hardcover,"John Brown is a man of many legacies, from her...","Nonfiction,History,Biography,Military History,...",https://i.gr-assets.com/images/S/compressed.ph...,307981533,9.78031E+12,https://goodreads.com/book/show/17320669-a-vol...,256,3.63,51,A Volcano Beneath the Snow: John Brown's War A...,156
99999,Marc E. Fitch,ebook,Did you know that interest in UFO research inc...,"Fantasy,Paranormal,Nonfiction",https://i.gr-assets.com/images/S/compressed.ph...,313382077,9.78031E+12,https://goodreads.com/book/show/17320689-paran...,398,3.83,3,"Paranormal Nation: Why America Needs Ghosts, U...",12

In [3]:
data_nueva.isnull().sum()

author              0
bookformat       3228
desc             6772
genre           10467
img              3045
isbn            14482
isbn13          11435
link                0
pages               0
rating              0
reviews             0
title               1
totalratings        0
dtype: int64

In [4]:
data_nueva.dropna(subset=['desc'], inplace=True)
data_nueva.isnull().sum()

author              0
bookformat       1732
desc                0
genre            7743
img              1240
isbn            12432
isbn13           9458
link                0
pages               0
rating              0
reviews             0
title               0
totalratings        0
dtype: int64

In [5]:
data_meli = pd.read_csv('data/books.csv')
data_meli

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0
6806,9788185944609,8185944601,Secrets Of The Heart,NaN,Khalil Gibran,Mysticism,http://books.google.com/books/content?id=XcrVp...,NaN,1993.0,4.08,74.0,324.0
6807,9788445074879,8445074873,Fahrenheit 451,NaN,Ray Bradbury,Book burning,NaN,NaN,2004.0,3.98,186.0,5733.0
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0

In [6]:
data_meli.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [7]:
data_meli.dropna(subset=['description'], inplace=True)
data_meli.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4257
authors             65
categories          37
thumbnail          222
description          0
published_year       5
average_rating      37
num_pages           37
ratings_count       37
dtype: int64

In [8]:
data2 = pd.read_csv('data/books2.csv')
data2

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,Bayou Moon,...,17204,18856,1180,105,575,3538,7860,6778,https://images.gr-assets.com/books/1307445460m...,https://images.gr-assets.com/books/1307445460s...
9996,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,Means of Ascent,...,12582,12952,395,303,551,1737,3389,6972,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
9997,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,The Mauritius Command,...,9421,10733,374,11,111,1191,4240,5180,https://images.gr-assets.com/books/1455373531m...,https://images.gr-assets.com/books/1455373531s...
9998,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,11279,11994,1988,275,1002,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...
9999,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,9162,9700,364,117,345,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...

In [9]:
data2.columns

Index(['id', 'book_id', 'best_book_id', 'work_id', 'books_count', 'isbn',
       'isbn13', 'authors', 'original_publication_year', 'original_title',
       'title', 'language_code', 'average_rating', 'ratings_count',
       'work_ratings_count', 'work_text_reviews_count', 'ratings_1',
       'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'image_url',
       'small_image_url'],
      dtype='object')

In [10]:
data2.drop(columns=['image_url','small_image_url',])

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,eng,4.25,3198671,3340896,72586,60427,117415,446835,1001952,1714267
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,eng,3.89,2683664,2773745,51992,86236,197621,606158,936012,947718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,Bayou Moon,...,eng,4.09,17204,18856,1180,105,575,3538,7860,6778
9996,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,Means of Ascent,...,eng,4.25,12582,12952,395,303,551,1737,3389,6972
9997,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,The Mauritius Command,...,eng,4.35,9421,10733,374,11,111,1191,4240,5180
9998,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,eng,3.65,11279,11994,1988,275,1002,3765,4577,2375
9999,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,NaN,4.00,9162,9700,364,117,345,2031,4138,3069

In [11]:
import numpy as np
data2['description'] = np.nan
data2['description'].isnull().sum()

10000

In [12]:
data2.drop_duplicates(subset='isbn13', keep='first', inplace=True)
data2.drop_duplicates(subset='title', keep='first', inplace=True)
data2.drop_duplicates(subset='isbn', keep='first', inplace=True)

In [13]:
book_data = pd.read_csv('data/book_data.csv')
book_data.head()

,book_authors,book_desc,book_edition,book_format,book_isbn,book_pages,book_rating,book_rating_count,book_review_count,book_title,genres,image_url
0,Suzanne Collins,Winning will make you famous. Losing means cer...,NaN,Hardcover,9.78044E+12,374 pages,4.33,5519135,160706,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,https://images.gr-assets.com/books/1447303603l...
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,US Edition,Paperback,9.78044E+12,870 pages,4.48,2041594,33264,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,https://images.gr-assets.com/books/1255614970l...
2,Harper Lee,The unforgettable novel of a childhood in a sl...,50th Anniversary,Paperback,9.78006E+12,324 pages,4.27,3745197,79450,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,https://images.gr-assets.com/books/1361975680l...
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,"Modern Library Classics, USA / CAN",Paperback,9.78068E+12,279 pages,4.25,2453620,54322,Pride and Prejudice,Classics|Fiction|Romance,https://images.gr-assets.com/books/1320399351l...
4,Stephenie Meyer,About three things I was absolutely positive.F...,NaN,Paperback,9.78032E+12,498 pages,3.58,4281268,97991,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,https://images.gr-assets.com/books/1361039443l...

In [14]:
book_data.drop_duplicates(subset='book_title', keep='first', inplace=True)

# concateno

In [15]:
import numpy as np

In [16]:
book_data.columns

Index(['book_authors', 'book_desc', 'book_edition', 'book_format', 'book_isbn',
       'book_pages', 'book_rating', 'book_rating_count', 'book_review_count',
       'book_title', 'genres', 'image_url'],
      dtype='object')

In [17]:
book_data['isbn'] = np.NaN

In [18]:
data_meli.columns

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='object')

In [19]:
data_nueva.columns

Index(['author', 'bookformat', 'desc', 'genre', 'img', 'isbn', 'isbn13',
       'link', 'pages', 'rating', 'reviews', 'title', 'totalratings'],
      dtype='object')

In [20]:
data_nueva.drop(columns=['bookformat', 'img','link', 'rating', 'reviews', 'totalratings'], inplace=True)
data_meli.drop(columns=['subtitle','thumbnail','published_year', 'average_rating', 'ratings_count'], inplace=True)
book_data.drop(columns=['book_edition', 'book_format', 'book_rating', 'book_rating_count', 'book_review_count', 'image_url'], inplace=True)

In [21]:
data_nueva.rename(columns={'desc': 'description', 'author':'authors'}, inplace=True)
data_meli.rename(columns={'isbn10': 'isbn','num_pages':'pages','categories':'genre'}, inplace=True)
book_data.rename(columns={'book_authors':'authors', 'book_desc':'description', 'book_isbn':'isbn13', 'book_title':'title','book_pages':'pages','genres':'genre'}, inplace=True)

In [22]:
concatenated_df = pd.concat([book_data, data_nueva, data_meli])
concatenated_df

,authors,description,isbn13,pages,title,genre,isbn
0,Suzanne Collins,Winning will make you famous. Losing means cer...,9.78044E+12,374 pages,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,NaN
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,9.78044E+12,870 pages,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,NaN
2,Harper Lee,The unforgettable novel of a childhood in a sl...,9.78006E+12,324 pages,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,NaN
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,9.78068E+12,279 pages,Pride and Prejudice,Classics|Fiction|Romance,NaN
4,Stephenie Meyer,About three things I was absolutely positive.F...,9.78032E+12,498 pages,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,NaN
...,...,...,...,...,...,...,...
6803,Hermann Hesse,This book tells the tale of a man who goes on ...,9788173031014,175.0,Journey to the East,Adventure stories,8173031010
6804,Robin Sharma,"Wisdom to Create a Life of Passion, Purpose, a...",9788179921623,198.0,The Monk Who Sold His Ferrari: A Fable About F...,Health & Fitness,817992162X
6805,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,This collection of the timeless teachings of o...,9788185300535,531.0,I Am that,Philosophy,8185300534
6808,Georg Wilhelm Friedrich Hegel,Since the three volume edition ofHegel's Philo...,9789027712059,210.0,The Berlin Phenomenology,History,9027712050
6809,Helena Grice;Tim Woods,This is a jubilant and rewarding collection of...,9789042003408,136.0,'I'm Telling You Stories',Literary Criticism,9042003405

In [23]:
concatenated_df.loc[concatenated_df['pages'].str.contains('pages', na=False), 'pages'] = concatenated_df.loc[concatenated_df['pages'].str.contains('pages', na=False), 'pages'].str.extract('(\d+)', expand=False).astype(int)
concatenated_df

,authors,description,isbn13,pages,title,genre,isbn
0,Suzanne Collins,Winning will make you famous. Losing means cer...,9.78044E+12,374,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,NaN
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,9.78044E+12,870,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,NaN
2,Harper Lee,The unforgettable novel of a childhood in a sl...,9.78006E+12,324,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,NaN
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,9.78068E+12,279,Pride and Prejudice,Classics|Fiction|Romance,NaN
4,Stephenie Meyer,About three things I was absolutely positive.F...,9.78032E+12,498,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,NaN
...,...,...,...,...,...,...,...
6803,Hermann Hesse,This book tells the tale of a man who goes on ...,9788173031014,175.0,Journey to the East,Adventure stories,8173031010
6804,Robin Sharma,"Wisdom to Create a Life of Passion, Purpose, a...",9788179921623,198.0,The Monk Who Sold His Ferrari: A Fable About F...,Health & Fitness,817992162X
6805,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,This collection of the timeless teachings of o...,9788185300535,531.0,I Am that,Philosophy,8185300534
6808,Georg Wilhelm Friedrich Hegel,Since the three volume edition ofHegel's Philo...,9789027712059,210.0,The Berlin Phenomenology,History,9027712050
6809,Helena Grice;Tim Woods,This is a jubilant and rewarding collection of...,9789042003408,136.0,'I'm Telling You Stories',Literary Criticism,9042003405

In [24]:
concatenated_df.title.nunique()

134726

In [25]:
concatenated_df.drop_duplicates(subset='title', keep='first', inplace=True)

In [26]:
concatenated_df

,authors,description,isbn13,pages,title,genre,isbn
0,Suzanne Collins,Winning will make you famous. Losing means cer...,9.78044E+12,374,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,NaN
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,9.78044E+12,870,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,NaN
2,Harper Lee,The unforgettable novel of a childhood in a sl...,9.78006E+12,324,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,NaN
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,9.78068E+12,279,Pride and Prejudice,Classics|Fiction|Romance,NaN
4,Stephenie Meyer,About three things I was absolutely positive.F...,9.78032E+12,498,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,NaN
...,...,...,...,...,...,...,...
6803,Hermann Hesse,This book tells the tale of a man who goes on ...,9788173031014,175.0,Journey to the East,Adventure stories,8173031010
6804,Robin Sharma,"Wisdom to Create a Life of Passion, Purpose, a...",9788179921623,198.0,The Monk Who Sold His Ferrari: A Fable About F...,Health & Fitness,817992162X
6805,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,This collection of the timeless teachings of o...,9788185300535,531.0,I Am that,Philosophy,8185300534
6808,Georg Wilhelm Friedrich Hegel,Since the three volume edition ofHegel's Philo...,9789027712059,210.0,The Berlin Phenomenology,History,9027712050
6809,Helena Grice;Tim Woods,This is a jubilant and rewarding collection of...,9789042003408,136.0,'I'm Telling You Stories',Literary Criticism,9042003405

In [28]:
data2.loc[data2['description'].isnull(),'title']= data2.loc[data2['description'].isnull(),'title'].apply(lambda x: x.split('(', 1)[0].strip() if '(' in x else x)
data2.loc[data2['description'].isnull(),'title']

0                                        The Hunger Games
1                   Harry Potter and the Sorcerer's Stone
2                                                Twilight
3                                   To Kill a Mockingbird
4                                        The Great Gatsby
                              ...
9995                                           Bayou Moon
9996                                      Means of Ascent
9997                                The Mauritius Command
9998    Cinderella Ate My Daughter: Dispatches from th...
9999                                  The First World War
Name: title, Length: 8991, dtype: object

In [29]:
merged_df = data2.merge(concatenated_df[['title', 'description','genre', 'pages']], on='title', how='left')
data2['description'] = merged_df['description_y'].fillna(data2['description'])
data2['genre'] = merged_df['genre']
data2['pages'] = merged_df['pages']

In [30]:
merged_df = data2.merge(concatenated_df[['isbn', 'description']], on='isbn', how='left')
data2['description'] = merged_df['description_y'].fillna(data2['description'])
data2['genre'] = merged_df['genre']
data2['pages'] = merged_df['pages']

In [31]:
merged_df = data2.merge(concatenated_df[['isbn13', 'description']], on='isbn13', how='left')
data2['description'] = merged_df['description_y'].fillna(data2['description'])
data2['genre'] = merged_df['genre']
data2['pages'] = merged_df['pages']

In [47]:
concatenated_df[concatenated_df['title'] == 'The Great Gatsby']

,authors,description,isbn13,title,isbn
29,F. Scott Fitzgerald,Alternate Cover Edition ISBN: 0743273567 (ISBN...,NaN,The Great Gatsby,NaN

In [32]:
data2.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,description,genre,pages
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,Winning will make you famous. Losing means cer...,Young Adult|Fiction|Science Fiction|Dystopia|F...,374
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,"In Harry Potter and the Sorcerer's Stone, Harr...",Fantasy|Young Adult|Fiction,320
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,About three things I was absolutely positive.F...,Young Adult|Fantasy|Romance|Paranormal|Vampire...,498
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,The unforgettable novel of a childhood in a sl...,Classics|Fiction|Historical|Historical Fiction...,324
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,Classics|Fiction|Academic|School|Literature|Hi...,180

In [33]:
data2.isnull().sum()

id                              0
book_id                         0
best_book_id                    0
work_id                         0
books_count                     0
isbn                            1
isbn13                          1
authors                         0
original_publication_year      18
original_title                427
title                           0
language_code                1010
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
description                     3
genre                           2
pages                           2
dtype: int64

In [34]:
data2.to_csv('data/books_joineado.csv')

In [38]:
data2.isnull().sum()

id                              0
book_id                         0
best_book_id                    0
work_id                         0
books_count                     0
isbn                            1
isbn13                          1
authors                         0
original_publication_year      18
original_title                427
title                           0
language_code                1010
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
description                    44
genre                          45
pages                          45
dtype: int64